server:
  port: 8081


spring:
  application:
    name: accounts
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:accounts
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

    show-sql: true